import styles from "@/styles/Home.module.css";

import Head from "next/head";
import fs from 'fs';
import path from 'path';
import { geistMono, geistSans } from "@/miscellaneous";
import { micromark } from 'micromark';

// 获取文件夹下所有文件的路径
const postsDirectory = path.join(process.cwd(), 'blogs');
const posts = fs.readdirSync(postsDirectory).map(filename => ({
    params: { slug: path.basename(filename, '.md') }
}));

type Params = {
    slug: string
}

export async function getStaticPaths() {
    return {
        paths: posts,
        fallback: false, // 如果设置为false，未匹配的路径将返回404
    };
}

export async function getStaticProps({ params }: { params: Params }) {
    // 根据文件名获取文件内容
    const postContent = fs.readFileSync(path.join(postsDirectory, `${params.slug}.md`), 'utf8');
    // 处理文件内容，例如解析Markdown等
    const content = micromark(postContent); // 这里应该是处理后的内容

    return {
        props: {
            content,
            params,
        },
    };
}

function Post({ content, params }: { content: string, params: Params }) {
    // 渲染页面
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
            <main className={styles.main}>
                <h1>My Post: {params.slug}</h1>
                <div dangerouslySetInnerHTML={{ __html: content }} />
            </main>
        </div>
    </>
};

export default Post;
