import styles from "@/styles/Home.module.css";

import Head from "next/head";
import fs from 'fs';
import path from 'path';
import { geistMono, geistSans } from "@/components/miscellaneous";
import { micromark } from 'micromark';

// 获取文件夹下所有文件的路径
const postsDirectory = path.join(process.cwd(), 'blogs');
const posts = fs.readdirSync(postsDirectory).map(filename => ({
    params: { slug: path.basename(filename, '.md') }
    // params: { slug: filename }
}));

type Params = {
    slug: string
}

export async function getStaticPaths() {
    return {
        paths: posts,
        fallback: false, // 如果设置为false，未匹配的路径将返回404
    };
}

const readContent = (filename: string) => {
    let filePath = path.join(postsDirectory, filename);
    const isPurefile = fs.existsSync(filePath + ".md");
    const isIndexFile = fs.existsSync(path.join(filePath, "index.md"));;
    if (isIndexFile && !isPurefile) {
        filePath = path.join(filePath, "index.md");
    } else if (!isIndexFile && isPurefile) {
        filePath += ".md"
    } else if (!isIndexFile && !isPurefile) {
        throw new Error(`文件夹${filePath}内没有index.md文件`);
    } else {
        throw new Error(`文件夹${filePath}内有重复的文件`);
    }
    const postContent = fs.readFileSync(filePath, 'utf8');
    return postContent;
}

export async function getStaticProps({ params }: { params: Params }) {
    const filename = params.slug;
    const date = filename.slice(0, 10);
    const title = filename.slice(11);
    // 根据文件名获取文件内容
    const postContent = readContent(filename);
    // 处理文件内容，例如解析Markdown等
    const content = micromark(postContent); // 这里应该是处理后的内容

    return {
        props: {
            content,
            title,
            params
        } as Props,
    };
}


type Props = {
    content: string,
    title: string,
    params: Params
}

function Post({ content, title, params }: Props) {
    // 渲染页面
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
            <main className={styles.main}>
                <h1>My Post: {title}</h1>
                <div dangerouslySetInnerHTML={{ __html: content }} />
            </main>
        </div>
    </>
};

export default Post;
