// pages/[...slug].tsx
import styles from "@/styles/Home.module.css";

import Head from "next/head";
import fs from 'fs';
import path from 'path';
import { geistMono, geistSans } from "@/components/miscellaneous";

// 获取文件夹下所有文件的路径
const postsDirectory = path.join(process.cwd(), 'blogs');
const postsNames: Params[] = fs.readdirSync(postsDirectory).map(filename => ({
    slug: path.basename(filename, '.md')
}));

type Params = {
    slug: string
}

export async function getStaticProps() {
    return {
        props: {
            posts: postsNames
        },
    };
}

function Post({ posts }: { posts: Params[] }) {
    // 渲染页面
    return <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
            <main className={styles.main}>
                {posts.map((v, i, arr) =>
                    <a
                        className={styles.primary}
                        href={`/blog/${v.slug}`}
                        // target="_blank"
                        rel="noopener noreferrer"
                    >
                        {v.slug}
                    </a>
                )}
            </main>
        </div>
    </>
};

export default Post;
