import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import Sidebar from "./sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={[inter.className, styles.container].join(' ')}>
      <Sidebar></Sidebar>
      {children}
    </div>
  );
}
