import type { ReactNode } from 'react'
import type { IconType } from 'react-icons'
import {
  LuBookOpen,
  LuBot,
  LuBoxes,
  LuBrain,
  LuBuilding2,
  LuCable,
  LuChartColumn,
  LuCloud,
  LuCode,
  LuDatabase,
  LuFileCode2,
  LuFileSpreadsheet,
  LuFlaskConical,
  LuFolder,
  LuGamepad2,
  LuGauge,
  LuGitPullRequest,
  LuGlobe,
  LuGraduationCap,
  LuHouse,
  LuImage,
  LuKeyRound,
  LuLanguages,
  LuLayoutPanelTop,
  LuMapPinned,
  LuMedal,
  LuMessageCircle,
  LuMusic4,
  LuNetwork,
  LuPackage,
  LuPalette,
  LuPenTool,
  LuPlug,
  LuPresentation,
  LuRefreshCw,
  LuRocket,
  LuScrollText,
  LuSearch,
  LuServer,
  LuSettings2,
  LuShield,
  LuSquareChartGantt,
  LuTags,
  LuTrophy,
  LuUserRound,
  LuUsers,
  LuUtilityPole,
  LuWrench,
  LuZap,
} from 'react-icons/lu'
import {
  SiCloudflare,
  SiCplusplus,
  SiDocusaurus,
  SiFastapi,
  SiGithubactions,
  SiGo,
  SiHuggingface,
  SiMarkdown,
  SiMinio,
  SiObsidian,
  SiOpenai,
  SiPostgresql,
  SiPytorch,
  SiPython,
  SiRust,
  SiSolana,
  SiSqlite,
  SiTauri,
  SiTraefikproxy,
  SiTypescript,
  SiWechat,
  SiWireguard,
  SiZhihu,
} from 'react-icons/si'

export type TagMeta = {
  label: string
  icon: ReactNode
}

const iconClassName = 'h-3.5 w-3.5'

function renderIcon(Icon: IconType) {
  return <Icon className={iconClassName} aria-hidden="true" />
}

function makeMeta(label: string, Icon: IconType): TagMeta {
  return { label, icon: renderIcon(Icon) }
}

export const tagMapping = {
  admin: makeMeta('Admin', LuSettings2),
  admission: makeMeta('Admission', LuGraduationCap),
  agent: makeMeta('Agent', LuBot),
  ai: makeMeta('AI', LuBrain),
  'ai-agent': makeMeta('AI Agent', LuBot),
  'algorithm-club': makeMeta('Algorithm Club', LuCode),
  architecture: makeMeta('Architecture', LuBuilding2),
  archive: makeMeta('Archive', LuPackage),
  authentication: makeMeta('Authentication', LuKeyRound),
  automation: makeMeta('Automation', LuBot),
  backend: makeMeta('Backend', LuServer),
  balancer: makeMeta('Balancer', LuChartColumn),
  bilibili: makeMeta('Bilibili', LuPresentation),
  bot: makeMeta('Bot', LuBot),
  'c++11': makeMeta('C++11', SiCplusplus),
  chat: makeMeta('Chat', LuMessageCircle),
  classification: makeMeta('Classification', LuTags),
  cloudflare: makeMeta('Cloudflare', SiCloudflare),
  'cloudflare-workers': makeMeta('Cloudflare Workers', SiCloudflare),
  cloudflared: makeMeta('cloudflared', SiCloudflare),
  codex: makeMeta('Codex', LuBot),
  combinator: makeMeta('Combinator', LuBoxes),
  compiler: makeMeta('Compiler', LuFileCode2),
  config: makeMeta('Config', LuSettings2),
  'config-distribution': makeMeta('Config Distribution', LuUtilityPole),
  content: makeMeta('Content', LuScrollText),
  coze: makeMeta('Coze', LuBot),
  'crafting-interpreters': makeMeta('Crafting Interpreters', LuBookOpen),
  csv: makeMeta('CSV', LuFileSpreadsheet),
  cto: makeMeta('CTO', LuBuilding2),
  customization: makeMeta('Customization', LuWrench),
  database: makeMeta('Database', LuDatabase),
  defi: makeMeta('DeFi', LuChartColumn),
  demo: makeMeta('Demo', LuFlaskConical),
  devops: makeMeta('DevOps', LuWrench),
  'disk-usage': makeMeta('Disk Usage', LuGauge),
  dns: makeMeta('DNS', LuGlobe),
  dns01: makeMeta('DNS-01', LuGlobe),
  docs: makeMeta('Docs', LuScrollText),
  docusaurus: makeMeta('Docusaurus', SiDocusaurus),
  'edge-computing': makeMeta('Edge Computing', LuCloud),
  education: makeMeta('Education', LuGraduationCap),
  english: makeMeta('English', LuLanguages),
  enrollment: makeMeta('Enrollment', LuGraduationCap),
  environment: makeMeta('Environment', LuGlobe),
  exam: makeMeta('Exam', LuPenTool),
  experiment: makeMeta('Experiment', LuFlaskConical),
  fastapi: makeMeta('FastAPI', SiFastapi),
  feeding: makeMeta('Feeding', LuPackage),
  filesystem: makeMeta('Filesystem', LuFolder),
  flclash: makeMeta('FlClash', LuShield),
  forwarding: makeMeta('Forwarding', LuRocket),
  frontend: makeMeta('Frontend', LuPalette),
  geoip: makeMeta('GeoIP', LuMapPinned),
  'github-actions': makeMeta('GitHub Actions', SiGithubactions),
  go: makeMeta('Go', SiGo),
  golang: makeMeta('Golang', SiGo),
  graduation: makeMeta('Graduation', LuTrophy),
  gui: makeMeta('GUI', LuLayoutPanelTop),
  hls: makeMeta('HLS', LuCable),
  homepage: makeMeta('Homepage', LuHouse),
  http: makeMeta('HTTP', LuGlobe),
  hypercorn: makeMeta('Hypercorn', LuServer),
  hysteria2: makeMeta('Hysteria2', LuRocket),
  identity: makeMeta('Identity', LuUserRound),
  image: makeMeta('Image', LuImage),
  infra: makeMeta('Infra', LuBuilding2),
  infrastructure: makeMeta('Infrastructure', LuBuilding2),
  iteration: makeMeta('Iteration', LuRefreshCw),
  kubernetes: makeMeta('Kubernetes', LuBoxes),
  kv: makeMeta('KV', LuDatabase),
  launch: makeMeta('Launch', LuRocket),
  llama: makeMeta('Llama', SiOpenai),
  lox: makeMeta('Lox', LuFileCode2),
  'luna-edge': makeMeta('luna-edge', LuCloud),
  'major-transfer': makeMeta('Major Transfer', LuRefreshCw),
  markdown: makeMeta('Markdown', SiMarkdown),
  'mesh-networking': makeMeta('Mesh Networking', LuNetwork),
  'message-queue': makeMeta('Message Queue', LuMessageCircle),
  micromark: makeMeta('micromark', SiMarkdown),
  'mini-program': makeMeta('Mini Program', LuLayoutPanelTop),
  minio: makeMeta('MinIO', SiMinio),
  mit: makeMeta('MIT', LuTags),
  mmdb: makeMeta('MMDB', LuDatabase),
  music: makeMeta('Music', LuMusic4),
  'netease-cloud-music': makeMeta('Netease Cloud Music', LuMusic4),
  network: makeMeta('Network', LuNetwork),
  nocobase: makeMeta('NocoBase', LuBoxes),
  nyc: makeMeta('NYC', LuBuilding2),
  nyu: makeMeta('NYU', LuGraduationCap),
  'object-storage': makeMeta('Object Storage', LuDatabase),
  obsidian: makeMeta('Obsidian', SiObsidian),
  oj: makeMeta('OJ', LuCode),
  oracle: makeMeta('Oracle', LuSearch),
  parser: makeMeta('Parser', LuFileCode2),
  plugin: makeMeta('Plugin', LuPlug),
  postgresql: makeMeta('PostgreSQL', SiPostgresql),
  pr: makeMeta('PR', LuGitPullRequest),
  product: makeMeta('Product', LuPackage),
  proxy: makeMeta('Proxy', LuShield),
  pwa: makeMeta('PWA', LuGlobe),
  python: makeMeta('Python', SiPython),
  quicksilver: makeMeta('Quicksilver', LuZap),
  r2: makeMeta('R2', LuCloud),
  refactor: makeMeta('Refactor', LuWrench),
  'reverse-engineering': makeMeta('Reverse Engineering', LuSearch),
  rfc: makeMeta('RFC', LuScrollText),
  roadmap: makeMeta('Roadmap', LuSquareChartGantt),
  runtime: makeMeta('Runtime', LuServer),
  rust: makeMeta('Rust', SiRust),
  score: makeMeta('Score', LuMedal),
  'self-hosting': makeMeta('Self Hosting', LuHouse),
  service: makeMeta('Service', LuServer),
  'sing-box': makeMeta('sing-box', LuPackage),
  'smart-contract': makeMeta('Smart Contract', LuFileCode2),
  'smart-manufacturing': makeMeta('Smart Manufacturing', LuWrench),
  'snake-game': makeMeta('Snake Game', LuGamepad2),
  socks5: makeMeta('SOCKS5', LuShield),
  solana: makeMeta('Solana', SiSolana),
  'source-code': makeMeta('Source Code', LuCode),
  sql: makeMeta('SQL', LuDatabase),
  sqlite: makeMeta('SQLite', SiSqlite),
  sqlparser: makeMeta('sqlparser', LuFileCode2),
  staking: makeMeta('Staking', LuChartColumn),
  startup: makeMeta('Startup', LuRocket),
  storage: makeMeta('Storage', LuDatabase),
  streaming: makeMeta('Streaming', LuCable),
  sync: makeMeta('Sync', LuRefreshCw),
  tandon: makeMeta('Tandon', LuGraduationCap),
  tauri: makeMeta('Tauri', SiTauri),
  'tch-rs': makeMeta('tch-rs', SiPytorch),
  teamwork: makeMeta('Teamwork', LuUsers),
  'tencent-cloud': makeMeta('Tencent Cloud', LuCloud),
  tju: makeMeta('TJU', LuGraduationCap),
  tls: makeMeta('TLS', LuShield),
  toefl: makeMeta('TOEFL', LuPenTool),
  traefik: makeMeta('Traefik', SiTraefikproxy),
  transformers: makeMeta('Transformers', SiHuggingface),
  trojan: makeMeta('Trojan', LuShield),
  'trojan-go': makeMeta('trojan-go', LuShield),
  typescript: makeMeta('TypeScript', SiTypescript),
  upsert: makeMeta('Upsert', LuRefreshCw),
  'venus-edge': makeMeta('venus-edge', LuCloud),
  vpn: makeMeta('VPN', LuShield),
  wechat: makeMeta('WeChat', SiWechat),
  windows: makeMeta('Windows', LuLayoutPanelTop),
  wireguard: makeMeta('WireGuard', SiWireguard),
  workerd: makeMeta('workerd', LuServer),
  writing: makeMeta('Writing', LuPenTool),
  zhihu: makeMeta('Zhihu', SiZhihu),
} satisfies Record<string, TagMeta>

export type Tag = keyof typeof tagMapping

export function getTagMeta(tag: Tag): TagMeta {
  return tagMapping[tag]
}
