import type { Tag } from './tagicon'

export type TimelinePoint = [year: number, month: number, day: number]

export type TimelineDate =
    | TimelinePoint
    | {
        start: TimelinePoint
        end: TimelinePoint
    }

export type TimelineItem = {
    date: TimelineDate
    title: string
    text: string
    tags: Tag[]
    kind: 'career' | 'demo' | 'project' | 'product' | 'solution' | 'trial'
    status?: 'archive' | 'active'
    url?: string
    branches?: string[]
}

export const timeline: TimelineItem[] = [
    {
        date: [2021, 9, 7],
        title: '天津大学入学',
        text: '进入天津大学智能制造专业开始本科学习。',
        tags: ['tju', 'smart-manufacturing', 'education', 'enrollment'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: [2022, 5, 30],
        title: '转专业到人工智能',
        text: '转入天津大学智能与计算学部人工智能专业继续本科学习。',
        tags: ['tju', 'ai', 'major-transfer', 'education'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: {
            start: [2023, 10, 11],
            end: [2023, 11, 13],
        },
        title: '天津大学算法社 TJUOJ 前端开发',
        text: '在天津大学算法社参与将 HOJ 修改为 TJUOJ 的工作，负责前端开发。',
        tags: ['tju', 'algorithm-club', 'frontend', 'oj'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: {
            start: [2024, 6, 10],
            end: [2025, 1, 3],
        },
        title: '多语言实现贪吃蛇',
        text: '先使用 C++ 实现贪吃蛇，随后又分别用 TypeScript 和 Rust 完成实现。',
        tags: ['c++11', 'typescript', 'rust', 'snake-game'],
        kind: 'demo',
        url: 'https://gitee.com/jabberwocky238/collections/496642',
    },
    {
        date: {
            start: [2024, 6, 2],
            end: [2024, 7, 25],
        },
        title: '在线课程平台开发',
        text: '使用 TypeScript 完成前后端开发，做了一个在线课程平台，包含上传、观看、权限管理以及 HLS 流媒体加密等能力。',
        tags: ['typescript', 'frontend', 'backend', 'hls', 'streaming'],
        kind: 'project',
    },
    {
        date: [2024, 9, 21],
        title: '托福最后一次考试',
        text: '最后一次 TOEFL 成绩为阅读 27、听力 21、口语 22、写作 25。历史最高单项分别为阅读 29、听力 27、口语 25、写作 25。',
        tags: ['toefl', 'english', 'exam', 'score'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: [2024, 9, 28],
        title: 'C++11 扫盘与文件夹体积计算项目',
        text: '基于 fs API 扫描磁盘，合并计算文件夹大小，并通过 CSV 缓存结果来减少重复扫描开销。',
        tags: ['c++11', 'filesystem', 'csv', 'disk-usage'],
        kind: 'demo',
        status: 'archive',
    },
    {
        date: [2024, 10, 8],
        title: 'Rust 版扫盘与文件夹体积计算项目',
        text: '使用 Rust 重新实现 fs API 扫盘、文件夹大小聚合计算和 CSV 缓存流程，进一步验证整体方案的可移植性和性能表现。',
        tags: ['rust', 'filesystem', 'csv', 'disk-usage'],
        kind: 'demo',
        status: 'archive',
    },
    {
        date: [2024, 10, 16],
        title: '微信公众号聊天机器人与动态回复系统',
        text: '实现微信公众号聊天机器人、动态回复和文件 feeding 流程，技术栈使用 Hypercorn + FastAPI。',
        tags: ['wechat', 'bot', 'fastapi', 'hypercorn', 'feeding'],
        kind: 'project',
    },
    {
        date: [2024, 11, 13],
        title: 'PWA 音乐平台短期项目',
        text: '开发了一个基于 PWA 的音乐平台，支持多端同步、自定义后端认证以及自部署后端。',
        tags: ['pwa', 'music', 'sync', 'authentication', 'self-hosting'],
        kind: 'project',
    },
    {
        date: [2024, 11, 20],
        title: '重写 transformers.model.LlamaForCasualLM 的部分实现',
        text: '使用 Python 配合 tch-rs，对 transformers.model.LlamaForCasualLM 的部分能力进行了重写和验证。',
        tags: ['python', 'tch-rs', 'transformers', 'llama'],
        kind: 'demo',
        status: 'archive',
    },
    {
        date: [2024, 12, 6],
        title: 'jw-micromark-toolbox',
        text: '一个 micromark 生态下的扩展语法插件，用于解析 Obsidian 风格的 Markdown 语法，比如 [[link]]、[[this is a link]]、![[this is an image.png]]、==this is highlight== 和 [modified link](/blog/or/may/be/not/blog)。项目已在 GitHub 开源，采用 MIT 许可。',
        tags: ['micromark', 'markdown', 'obsidian', 'plugin', 'mit'],
        kind: 'solution',
        status: 'active',
        url: 'https://github.com/Jabberwocky238/jw-micromark-toolbox',
    },
    {
        date: [2025, 1, 3],
        title: '读完 Crafting Interpreters 并实现 Rust 版 Lox',
        text: '完整读完 Crafting Interpreters，完成 Java Lox 和 C Lox 的全部练习部分，并使用 Rust 完整实现了 Lox 编译器。',
        tags: ['rust', 'compiler', 'lox', 'crafting-interpreters'],
        kind: 'solution',
        url: 'https://gitee.com/jabberwocky238/lox',
        branches: ['compiler-construction'],
    },
    {
        date: [2025, 1, 21],
        title: 'environmentor',
        text: '基于 Rust + Tauri 开发的环境变量管理器 GUI，已在 Windows 上完成完整测试。',
        tags: ['rust', 'tauri', 'gui', 'windows', 'environment'],
        kind: 'project',
        status: 'archive',
        url: 'https://github.com/Jabberwocky238/environmentor',
    },
    {
        date: [2025, 2, 23],
        title: '网易云 API 逆向项目',
        text: '完成网易云 API 逆向，并使用 NocoBase Admin 进行管理。',
        tags: ['reverse-engineering', 'netease-cloud-music', 'nocobase', 'admin'],
        kind: 'project',
        url: 'https://gitee.com/jabberwocky238/11112222',
    },
    {
        date: [2025, 3, 12],
        title: 'NYU Tandon 录取',
        text: '收到 NYU Tandon 的录取结果。',
        tags: ['nyu', 'tandon', 'admission', 'education'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: [2025, 3, 14],
        title: '参与 Infinite Galaxy 项目',
        text: '参与学生发起的小程序开发项目 Infinite Galaxy，负责前端、后端以及数据库管理工作。',
        tags: ['mini-program', 'frontend', 'backend', 'database', 'teamwork'],
        kind: 'project',
        branches: ['education'],
    },
    {
        date: {
            start: [2025, 3, 29],
            end: [2025, 12, 1],
        },
        title: '基于 FlClash 的魔改开发',
        text: '持续开发基于 FlClash 的魔改版本，使其支持自定义认证和配置获取流程，现已废弃。',
        tags: ['flclash', 'authentication', 'config', 'network', 'customization'],
        kind: 'project',
        status: 'archive',
    },
    {
        date: [2025, 6, 11],
        title: '天津大学人工智能专业毕业',
        text: '于天津大学人工智能专业完成本科学业并毕业。',
        tags: ['tju', 'ai', 'graduation', 'education'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: [2025, 6, 26],
        title: 'easy-coze',
        text: '使用 Coze 平台搭建了一个简单的 agent 对话界面，并以 2000 人民币成交。',
        tags: ['coze', 'agent', 'chat', 'product'],
        kind: 'product',
        status: 'archive',
    },
    {
        date: [2025, 7, 25],
        title: 'gasoline',
        text: '开启项目 gasoline。Gasoline 是一个受 WireGuard 启发的 mesh networking tool，支持可定制传输层，面向抗审查与网络穿透场景，支持 Trojan 和 TLS，并持续更新中。',
        tags: ['wireguard', 'mesh-networking', 'tls', 'trojan', 'network'],
        kind: 'project',
        status: 'active',
        url: 'https://github.com/Jabberwocky238/gasoline',
        branches: ['network-stack'],
    },
    {
        date: [2025, 8, 1],
        title: '创立 enzyme.cloud',
        text: '创立 enzyme.cloud，提供 SOCKS5 VPN 代理服务。',
        tags: ['socks5', 'vpn', 'proxy', 'service'],
        kind: 'product',
        branches: ['network-stack', 'entrepreneurship'],
    },
    {
        date: [2025, 8, 24],
        title: 'NYU Tandon 入学',
        text: '正式入学 NYU Tandon，开始新的学习阶段。',
        tags: ['nyu', 'tandon', 'enrollment', 'education'],
        kind: 'career',
        branches: ['education'],
    },
    {
        date: [2025, 9, 11],
        title: 'rfc-archive',
        text: '创建项目 rfc-archive，用 Docusaurus 记录自己阅读过的 RFC 文档。项目持续约一个月，现已归档，但 rfc.archive238.com 仍可访问。',
        tags: ['rfc', 'docusaurus', 'docs', 'archive'],
        kind: 'project',
        status: 'archive',
        url: 'https://github.com/Jabberwocky238/rfc-archive',
    },
    {
        date: [2025, 9, 15],
        title: '加入 K&M ERA 担任 CTO',
        text: '加入纽约学生创业组织 K&M ERA，担任 CTO，负责 Solana 合约开发。',
        tags: ['cto', 'solana', 'smart-contract', 'startup', 'nyc'],
        kind: 'career',
        branches: ['entrepreneurship'],
    },
    {
        date: [2025, 9, 17],
        title: 'ratemygirls',
        text: '开启 ratemygirls 项目：使用 Bilibili 机器人账号，自动根据 @ 和回复内容抓取笔记图片并上传到 R2 存储桶，同时分析文字部分携带的 tag，对图片进行自动分类。',
        tags: ['bilibili', 'bot', 'r2', 'image', 'classification'],
        kind: 'project',
    },
    {
        date: {
            start: [2025, 9, 25],
            end: [2025, 11, 13],
        },
        title: '系统性研究 WireGuard 源码',
        text: '开始系统性研究 WireGuard 源码，并撰写《wireguard源码解析》系列文章 4 篇。',
        tags: ['wireguard', 'source-code', 'network', 'zhihu', 'writing'],
        kind: 'solution',
        url: 'https://www.zhihu.com/column/c_1970274841656525692',
        branches: ['network-stack'],
    },
    {
        date: [2025, 11, 27],
        title: '完成合约 anyswap',
        text: '在 Solana 平台上完整复现了 Balancer 算法，实现了合约 anyswap。',
        tags: ['solana', 'smart-contract', 'balancer', 'defi'],
        kind: 'solution',
        url: 'https://github.com/K-M-official/anyswap',
    },
    {
        date: [2025, 12, 13],
        title: '二次开发 trojan-go',
        text: '对 trojan-go 进行二次开发，使其支持通过 HTTP 验证，并与 hysteria2 server 保持同一套接口设计。',
        tags: ['trojan-go', 'http', 'authentication', 'hysteria2', 'network'],
        kind: 'solution',
        branches: ['network-stack'],
    },
    {
        date: [2026, 1, 2],
        title: '完成合约 multistake',
        text: '完成 Solana 平台合约 multistake，实现权重质押池与 oracle 预言机动态同步权重。',
        tags: ['solana', 'smart-contract', 'staking', 'oracle', 'defi'],
        kind: 'solution',
        url: 'https://github.com/K-M-official/multistake',
    },
    {
        date: {
            start: [2026, 1, 12],
            end: [2026, 2, 2],
        },
        title: 'combinator',
        text: '开启项目 combinator，使用 Go 语言尝试将数据库 SQL、KV 缓存、消息队列和对象存储服务合并为统一网关，后于 2026-02-02 废弃。',
        tags: ['golang', 'sql', 'kv', 'message-queue', 'object-storage'],
        kind: 'project',
        status: 'archive',
        branches: ['combinator'],
    },
    {
        date: [2026, 1, 18],
        title: 'combinator-action',
        text: '开发 combinator-action，让用户可以通过 GitHub Actions 集成对 combinator 的 upsert。',
        tags: ['github-actions', 'combinator', 'upsert', 'automation'],
        kind: 'solution',
        url: 'https://github.com/Jabberwocky238/combinator-action',
        branches: ['combinator'],
    },
    {
        date: [2026, 1, 22],
        title: '修改 sing-box 并提交 PR',
        text: '修改 sing-box 以支持腾讯云 DNS-01 和 HTTP 认证，并提交了 PR。',
        tags: ['sing-box', 'dns01', 'http', 'pr', 'tencent-cloud'],
        kind: 'solution',
        branches: ['network-stack'],
    },
    {
        date: [2026, 1, 28],
        title: '扩展 go-sqlparser 支持 SQLite 与 PostgreSQL',
        text: '修改 sqlparser，使其支持 SQLite 和 PostgreSQL 双语法解析，覆盖 SQLite 全部语法以及 PostgreSQL 的主要部分。',
        tags: ['go', 'sqlparser', 'sqlite', 'postgresql', 'parser'],
        kind: 'solution',
        url: 'https://github.com/Jabberwocky238/sqlparser',
        branches: ['combinator'],
    },
    {
        date: [2026, 2, 11],
        title: 'exhibitor',
        text: '示例项目 exhibitor，基于 combinator 架构进行的一次类边缘计算实验。',
        tags: ['combinator', 'edge-computing', 'experiment', 'demo'],
        kind: 'trial',
        url: 'https://github.com/Jabberwocky238/exhibitor',
        branches: ['combinator'],
    },
    {
        date: [2026, 2, 12],
        title: '开始系统学习 Kubernetes',
        text: '阅读 Traefik 源码后，确认 Kubernetes 和 DevOps 是更值得投入的方向，开始系统学习 Kubernetes，并决定彻底终止 combinator 计划。',
        tags: ['traefik', 'kubernetes', 'devops', 'source-code', 'architecture'],
        kind: 'career',

    },
    {
        date: [2026, 2, 13],
        title: '完成 luna-dns',
        text: '完成 luna-dns，在自定义 Kubernetes 体系下实现 DNS 服务，设计上比 PowerDNS 更简单，并支持 GeoIP MMDB 计算与 forwarding。',
        tags: ['kubernetes', 'dns', 'geoip', 'mmdb', 'forwarding'],
        kind: 'solution',
        url: 'https://github.com/Jabberwocky238/luna-dns',

    },
    {
        date: [2026, 2, 19],
        title: '开启 durableobject 项目',
        text: '开启 durableobject 项目，目标是复刻 Cloudflare Worker 的底层架构，并同时开始深度研究 workerd 与 cloudflared 源码。',
        tags: ['cloudflare-workers', 'workerd', 'cloudflared', 'runtime', 'source-code'],
        kind: 'trial',
        branches: ['cloud-native', 'edge-computing'],
    },
    {
        date: {
            start: [2026, 3, 11],
            end: [2026, 3, 14],
        },
        title: 'fs3 短线项目',
        text: '进行为期四天的短线项目 fs3，目标是从底层存储字节分布到 API 表现与性能都尽可能与 MinIO 完全一致，并探索 AI agent 编程极限。最终测试表明，即使有人类大量介入，Claude Opus 4.6 和 Codex 5.4 仍无法胜任该问题。',
        tags: ['rust', 'minio', 'ai-agent', 'experiment', 'storage'],
        kind: 'trial',
        status: 'archive',
        url: 'https://github.com/Jabberwocky238/fs3',
        branches: ['cloud-native', 'agent-programming'],
    },
    {
        date: [2026, 3, 21],
        title: '终止 luna-edge 项目',
        text: '终止 luna-edge 项目。该项目尝试合并 luna-ingress 与 luna-dns，目标是复刻 Cloudflare Quicksilver 配置分发网络。',
        tags: ['luna-edge', 'quicksilver', 'config-distribution', 'cloudflare', 'infrastructure'],
        kind: 'trial',
        status: 'archive',
    },
    {
        date: [2026, 3, 23],
        title: '完成 venus-edge',
        text: '在 Codex 5.4 帮助下完成 venus-edge，充分使用 infra 思想，大幅降低系统复杂度并覆盖 luna-edge 的全部功能，代码量相比原方案降低约 95%。',
        tags: ['venus-edge', 'infra', 'architecture', 'refactor', 'codex'],
        kind: 'solution',
        status: 'active',
        branches: ['cloud-native', 'agent-programming'],
    },
    {
        date: [2026, 3, 29],
        title: '创立 jabberwocky238.github.io',
        text: '把这里作为个人主页的起点，用来记录项目、想法和正在做的事情。',
        tags: ['homepage', 'launch', 'identity'],
        kind: 'project',
        status: 'active',
    },
]
